import cv2
import numpy as np

import asyncio
from pathlib import Path

from typing import AsyncGenerator, List, Dict
from typing_extensions import override

from google.genai.types import Content
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob

from src.logger import logger
from src.agents.experts.image_processing.tool import image_processing_tool


class ImageProcessingAgent(BaseAgent):
    """
    a custom agent for image processing.
    """

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
            self,
            name: str,
            description: str = ""
    ):
        super().__init__(
            name=name,
            description=description
        )


    def format_event(self, content_text: str = None, state_delta: Dict = None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the ImageBasicOperationAgent asynchronously.
        This method perform basic operation on a single image.
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        current_parameters = ctx.session.state.get('current_parameters', {})
        logger.info('enter ImageProcessingAgent')

        if 'input_name' not in current_parameters or 'processing_type' not in current_parameters:
            error_text = "提供给 ImageProcessingAgent 的参数缺失，必须包含：input_name 和 processing_type"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})

            return

        input_img_name = current_parameters.get('input_name', [])
        processing_type = current_parameters.get('processing_type', '')

        if isinstance(input_img_name, str):
            input_img_name = [input_img_name]

        img_binary_list = []
        for name in input_img_name:
            art_part = await ctx.artifact_service.load_artifact(filename=name, app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id)
            img_binary_list.append(art_part.inline_data.data)

        result = await image_processing_tool(img_binary_list, processing_type)

        # logger.info(result)
        step = ctx.session.state['step']
        if result["status"] == "error":
            error_text = f"执行步骤{step + 1}: {self.name}执行出错：{result['message']}"
            current_output = {"status": "error", "message": error_text}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        else:
            text = f"执行步骤{step + 1}: {self.name}：图片处理完成"
            description = ''
            output_artifacts = []

            # logger.info(input_img_name)
            for i, img in enumerate(result["message"]):
                name_before = input_img_name[i]
                name_before_file = name_before.split('.')[0]
                artifact_name = f"step{ctx.session.state.get('step') + 1}_{name_before_file}_image_processing_output.png"
                # logger.info(artifact_name)
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=img))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
                    filename=artifact_name, artifact=artifact_part
                )

                description = f"文件{name_before}基本操作处理之后得到的图片"
                output_artifacts.append({'name': artifact_name, 'description': description})

                text += f"\nimage processing 图片保存成功，输出图片名称为{artifact_name}"

            current_output = {
                "status": "success",
                "message": text,
                "output_artifacts": output_artifacts
            }
            yield self.format_event(text, {'current_output': current_output})
            return








