from typing import AsyncGenerator, List, Dict
from typing_extensions import override
from concurrent.futures import ThreadPoolExecutor
import time
import asyncio
from PIL import Image



from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Content, Blob

from src.logger import logger
from conf.system import SYS_CONFIG
from src.agents.experts.image_editing.tool import (segmind_GPT_image_1_tool,
                                                   prompt_enhancement_tool,
                                                   nano_banana_image_edit_tool,
                                                   seedream_image_edit_tool
                                                   )
from src.agents.experts.image_utils import get_image_info_from_bytes
from server.services.token_usage_service import token_usage_service


# Sequential Agent
# Prompt-Enhanced -> ImageGeneration


class ImageGenerationAndEditingAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""

    model_config = {"arbitrary_types_allowed": True}

    def __init__(self, name: str, description: str = "") -> None:
        """Initializes the ImageEditingAgent."""

        super().__init__(name=name, description=description)

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the ImageEditingAgent asynchronously.

        This method orchestrates the sequence of agents to generate an image from text.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image editing process.
        """
        current_parameters = ctx.session.state.get('current_parameters', {})

        if ('input_name' not in current_parameters) or ('prompt' not in current_parameters):
            error_text = f"提供给{self.name}的参数缺失，必须包含：input_name，prompt"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})
            return

        img_edit_name = 'nano_banana'
        if 'tool_name' in current_parameters:
            img_edit_name = current_parameters['tool_name']
        original_prompt = current_parameters['prompt']
        if isinstance(original_prompt, str):
            original_prompt = [original_prompt]
        logger.debug(f"{self.name}:  prompt before enhancement: " + '\n\n'.join(original_prompt))

        # prompt enhancement
        tasks = [prompt_enhancement_tool(SYS_CONFIG.llm_model, ctx, prompt) for prompt in original_prompt]
        result_list = await asyncio.gather(*tasks)
        enhanced_prompt_list = []
        for i, result in enumerate(result_list):
            if result['status'] == 'success':
                enhanced_prompt_list = enhanced_prompt_list + result['message']
            else:
                logger.warning(f"{self.name}: prompt enhancement failed; using the original prompt")
                enhanced_prompt_list.append(original_prompt[i])

        logger.debug(f"{self.name}: prompt after enhancement: " + '\n\n'.join(enhanced_prompt_list))

        if img_edit_name == 'gpt_image':
            rsp = await segmind_GPT_image_1_tool(ToolContext(ctx), enhanced_prompt_list)
        elif img_edit_name == 'seedream':
            rsp = await seedream_image_edit_tool(ToolContext(ctx), enhanced_prompt_list)
        else:
            rsp = await nano_banana_image_edit_tool(ToolContext(ctx), enhanced_prompt_list)

        step = ctx.session.state['step']

        if rsp["status"] == "error":
            error_text = f"执行步骤{step+1}: {self.name}执行出错：{rsp['message']}"
            message_for_user = f"执行步骤执行出错：{rsp['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user':message_for_user, 'output_text':''}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output":current_output}) 
            return
        
        else:
            usage_list = rsp.get("usage_list", [])
            for usage in usage_list:
                if isinstance(usage, dict):
                    await token_usage_service.record_external_usage(
                        user_id=ctx.session.user_id,
                        session_id=ctx.session.id,
                        component="expert_tool",
                        agent_name=self.name,
                        model_name=rsp.get("model_name"),
                        usage=usage,
                    )
            prompt_list = current_parameters['prompt']
            if not isinstance(prompt_list, list):
                prompt_list = [prompt_list]
            text = f"执行步骤{step+1}: {self.name}：{len(prompt_list)}张图片编辑已完成"
            message_for_user = f"当前执行步骤{len(prompt_list)}张图片编辑已完成"
            output_artifacts = []

            for i, (prompt, message) in enumerate(zip(enhanced_prompt_list, rsp['message'])):
                if (not message) or (isinstance(message, str)):
                    text += f"\n第{i+1}张图片编辑失败，prompt为{prompt}。"

                artifact_name = f"step{ctx.session.state.get('step')+1}_editing_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=message))

                await ctx.artifact_service.save_artifact(app_name=ctx.session.app_name,
                                                         user_id=ctx.session.user_id,
                                                         session_id=ctx.session.id,
                                                         filename=artifact_name,
                                                         artifact=artifact_part
                                                         )

                # if isinstance(message, str):
                #     logger.info(message)
                #     print(message)
                basic_info = get_image_info_from_bytes(message) # N
                text += f"\n第{i+1}张图片编辑成功，输出图片名称为{artifact_name}"
                description = f"在原图片{current_parameters['input_name']}基础上编辑得到的图片，编辑指令为：{prompt} \n\n生成后的图像基本信息为：{basic_info}"
                
                output_artifacts.append({'name': artifact_name, 'description': description})

            current_output = {"author": self.name,
                              "status": "success",
                              "message": text,
                              "message_for_user": message_for_user,
                              "output_artifacts": output_artifacts,
                              'output_text': ''
                              }
            yield self.format_event(text, {'current_output': current_output})
            return
