from typing import AsyncGenerator, List, Dict
from typing_extensions import override
import time
import asyncio
import base64

import mimetypes

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob, Content
from google.genai import types

from src.logger import logger
from src.agents.experts.video_generation.tool import (prompt_enhancement_tool,
                                                      seedance_video_generation_tool,
                                                      veo_video_generation_tool)
from server.services.token_usage_service import token_usage_service


class VideoGenerationAgent(BaseAgent):
    """Generate videos from text prompts, image frames, or reference images."""
    model_config = {"arbitrary_types_allowed": True}

    def __init__(
            self,
            name: str,
            description: str = "",
    ) -> None:
        """Initializes the ImageGenerationAgent."""

        sub_agents_list: List[BaseAgent] = []
        super().__init__(
            name=name,
            sub_agents=sub_agents_list,
            description=description,
        )

    def format_event(self, content_text: str = None, state_delta: Dict = None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        # design_suggestions = InvocationContext.state.get('design_suggestions', '')
        # if design_suggestions and len(design_suggestions) > 0:

        current_parameters = ctx.session.state.get('current_parameters', {})
        tool_name = 'seedance'
        prompt = ''
        input_img_list = []
        mode = 'prompt'
        aspect_ratio = '16:9'
        if 'tool_name' in current_parameters:
            tool_name = current_parameters['tool_name']
        if 'prompt' in current_parameters:
            prompt = current_parameters['prompt']
        if 'input_img_list' in current_parameters:
            input_img_list = current_parameters['input_img_list']
        if 'mode' in current_parameters:
            mode = current_parameters['mode']

        if 'aspect_ratio' in current_parameters:
            aspect_ratio = current_parameters['aspect_ratio']
        if 'aspect_ratio' not in {'16:9', '9:16'}:
            aspect_ratio = '16:9'

        if ('prompt' not in current_parameters and 'input_img_list' not in current_parameters) :
            error_text = f"提供给{self.name}的参数缺失，必须包含： prompt 或者 input_img_list"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'output_text': ''}
            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        if mode not in {'prompt', 'first_frame', 'first_frame_and_last_frame', 'reference_asset', 'reference_style'}:
            error_text = f"提供给{self.name}的 mode 错误，现在的值是{mode}。正确的值必须是 'prompt', 'first_frame', 'first_frame_and_last_frame', 'reference_asset', 'reference_style' 之一"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'output_text': ''}
            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        if mode != 'prompt' and (not isinstance(input_img_list, list) or len(input_img_list) == 0):
            error_text = f"提供给{self.name}的 input_img_list 错误，必须是 list 类型 并且有元素 " + str(input_img_list)
            current_output = {"author": self.name, "status": "error", "message": error_text, 'output_text': ''}
            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return



        original_prompt = prompt
        if isinstance(original_prompt, str):
            original_prompt = [original_prompt]
        logger.debug('prompt before enhancement: ' + '\n'.join(original_prompt))

        # prompt enhancement

        if len('\n'.join(original_prompt)) > 0:
            tasks = [prompt_enhancement_tool(ctx, prompt) for prompt in original_prompt]
            result_list = await asyncio.gather(*tasks)
            prompt_list = []
            for i, result in enumerate(result_list):
                if result['status'] == 'success':
                    prompt_list.append(result['message'])
                else:
                    logger.warning(f"{self.name}: prompt enhancement failed; using the original prompt")
                    prompt_list.append(original_prompt[i])
        else:
            prompt_list = original_prompt
        logger.debug('prompt after enhancement: ' + '\n'.join(prompt_list))

        img_obj_list_for_veo = []
        img_obj_list_for_seedance = []
        logger.info(input_img_list)
        for file_name in input_img_list:
            art_part = await ctx.artifact_service.load_artifact(filename=file_name,
                                                                app_name=ctx.session.app_name,
                                                                user_id=ctx.session.user_id,
                                                                session_id=ctx.session.id)
            img_data = art_part.inline_data.data
            mime_type, _ = mimetypes.guess_type(file_name)

            base64_data = base64.b64encode(img_data).decode('utf-8')
            img_base64=  f"data:{mime_type};base64,{base64_data}"
            img_obj_list_for_seedance.append(img_base64)

            # for veo
            image = types.Image(image_bytes=img_data, mime_type=mime_type)
            img_obj_list_for_veo.append(image)


        if tool_name == 'seedance': #
            tasks = [seedance_video_generation_tool(prompt, img_obj_list_for_seedance, mode, aspect_ratio) for prompt in prompt_list]
            result_list = await asyncio.gather(*tasks)
        else:
            tasks = [veo_video_generation_tool(prompt, img_obj_list_for_veo, mode, aspect_ratio) for prompt in prompt_list]
            result_list = await asyncio.gather(*tasks)


        output_artifacts = []
        message = []
        for i, (prompt, result) in enumerate(zip(prompt_list, result_list)):
            usage = result.get("usage")
            if isinstance(usage, dict):
                await token_usage_service.record_external_usage(
                    user_id=ctx.session.user_id,
                    session_id=ctx.session.id,
                    component="expert_tool",
                    agent_name=self.name,
                    model_name=result.get("model_name"),
                    usage=usage,
                )
            if result['status'] == 'error':
                message.append(f"第{i + 1}个视频生成失败，原因：{result['message']}")
            else:
                message.append(f"第{i + 1}个视频生成成功")
                artifact_name = f"step{ctx.session.state.get('step') + 1}_video_generation_output{i}.mp4"
                artifact_part = Part(inline_data=Blob(mime_type='video/mp4',
                                                      data=result["message"]))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
                    filename=artifact_name, artifact=artifact_part
                )

                description = f"第{ctx.session.state.get('step') + 1}步由视频生成工具生成的第{i + 1}张视频，prompt为：{prompt}"
                output_artifacts.append({'name': artifact_name, 'description': description})

        if len(output_artifacts) == 0:
            message = f"全部{len(result_list)}张视频生成失败。{','.join(message)}"
            message_for_user = f"全部{len(result_list)}张视频生成失败。{','.join(message)}"
            logger.error(message)
            current_output = {"author": self.name, 'status': 'error', 'message': message,
                              'message_for_user': message_for_user, 'output_text': ''}

        else:
            message = f"已完成{len(result_list)}个任务的生成：{','.join(message)}"
            message_for_user = f"已完成任务的视频生成工作"
            logger.info(message)
            current_output = {"author": self.name, 'status': 'success', 'message': message,
                              'message_for_user': message_for_user, 'output_artifacts': output_artifacts,
                              'output_text': ''}

        yield self.format_event(message, {"current_output": current_output})
        return
