import asyncio
from pathlib import Path
import json
from playwright.async_api import async_playwright

from typing import AsyncGenerator, List, Dict
from typing_extensions import override

from google.genai.types import Content
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob

from src.logger import logger
from src.agents.experts.html_to_image.tool_v3 import html_to_image
from src.utils import clean_json_string

class HTMLToImageAgent(BaseAgent):
    """
    a custom agent for search image or text
    """

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
            self,
            name: str,
            description: str = ""
    ):
        super().__init__(
            name=name,
            description=description
        )


    def format_event(self, content_text: str = None, state_delta: Dict = None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the HTMLTOImage asynchronously.
        This method achieves transform html page to a single image.
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        current_parameters = ctx.session.state.get('current_parameters', {})
        html_result_by_agent = ctx.session.state.get('html_code_by_agent', '')
        pgbr_final_results = ctx.session.state.get('page_generation_by_reference/final_results', {})
        ui_result = ctx.session.state.get('ui/code_output', '')
        suggested_width = 1024
        suggested_height = 768

        logger.info(html_result_by_agent)
        html_code_by_agent = None
        if isinstance(html_result_by_agent, str) and len(html_result_by_agent) > 7:
            if html_result_by_agent[:7] == '```html':
                html_code_by_agent = html_result_by_agent[7:]
                html_code_by_agent = html_code_by_agent.strip('`')
            elif html_result_by_agent[:7] == '```json':
                html_code_by_agent = html_result_by_agent[7:]
                html_code_by_agent = html_code_by_agent.strip('`')
                if 'html_code' in html_code_by_agent:
                    html_code_json = json.loads(html_code_by_agent)
                    html_code_by_agent = html_code_json['html_code']
            else:
                html_result_by_agent = clean_json_string(html_result_by_agent)
                html_result_json = json.loads(html_result_by_agent)
                if 'html_code' in html_result_json:
                    html_code_by_agent = html_result_json['html_code']
                if 'suggested_width' in html_result_json:
                    suggested_width = html_result_json['suggested_width']
                if 'suggested_height' in html_result_json:
                    suggested_height = html_result_json['suggested_height']
        elif isinstance(html_result_by_agent, dict):
            if 'html_code' in html_result_by_agent:
                html_code_by_agent = html_result_by_agent['html_code']
            if 'suggested_width' in html_result_by_agent:
                suggested_width = html_result_by_agent['suggested_width']
            if 'suggested_height' in html_result_by_agent:
                suggested_height = html_result_by_agent['suggested_height']
        elif isinstance(html_result_by_agent, list):
            pass

        if  isinstance(ui_result, str) and len(ui_result) > 0:
            logger.info(ui_result)
            if ui_result[:7] == '```html':
                ui_result = ui_result[7:]
                ui_result = ui_result.strip('`')
            logger.info(ui_result)
            # ui_result = clean_json_string(ui_result)
            # ui_result = json.loads(ui_result)


        if 'html_code' not in current_parameters:
            error_text = "提供给HTMLToImageAgent的参数缺失，必须包含：html_code"
            current_output = {"author": self.name, "status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})

            return


        html_code = current_parameters['html_code']
        logger.info(html_code)
        if isinstance(html_code, str) and len(html_code) > 7:
            if html_code[:7] == '```html':
                html_code = html_code[7:]
                html_code = html_code.strip('`')
            elif html_code[:7] == '```json':
                html_code = html_code[7:]
                html_code = html_code.strip('`')
            if 'html_code' in html_code:
                html_code = clean_json_string(html_code)
                html_code_json = json.loads(html_code)
                html_code = html_code_json['html_code']
        elif isinstance(html_code, dict):
            if 'html_code' in html_code:
                html_code = html_code['html_code']

        if isinstance(html_code_by_agent, str) and len(html_code_by_agent) > len(html_code):
            html_code = html_code_by_agent

        logger.info(html_code_by_agent)
        logger.info(html_code)
        if len(ui_result) > len(html_code):
            html_code = ui_result
            logger.info(html_code)

        input_img_name = current_parameters.get('input_img_name', [])

        if 'suggested_width' in current_parameters:
            suggested_width = current_parameters['suggested_width']
        if 'suggested_height' in current_parameters:
            suggested_height = current_parameters['suggested_height']

        img_binary_list = []
        logger.info(input_img_name)
        for name in input_img_name:
            art_part = await ctx.artifact_service.load_artifact(filename=name, app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id)
            if art_part is not None:
                img_binary_list.append((name, art_part.inline_data.data))
        result = await html_to_image(html_code, img_binary_list, suggested_width, suggested_height)

        # logger.info(result)
        step = ctx.session.state['step']
        if result["status"] == "error":
            error_text = f"执行步骤{step + 1}: {self.name}执行出错：{result['message']}"
            message_for_user = f"执行步骤执行出错：{result['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user': message_for_user, 'output_text':''}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        else:
            text = f"执行步骤{step + 1}: {self.name}：从html转图片完成"
            message_for_user = "执行步骤从html转图片完成"
            output_artifacts = []

            artifact_name = f"step{ctx.session.state.get('step') + 1}_html2img_output.png"
            artifact_part = Part(inline_data=Blob(mime_type='image/png', data=result['message']))

            await ctx.artifact_service.save_artifact(
                app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
                filename=artifact_name, artifact=artifact_part
            )

            text += f"\nhtml2img图片保存成功，输出图片名称为{artifact_name}"
            description = f"html文件转换得到的图片。\nhtml_code：{html_code}\n\n"

            output_artifacts.append({'name': artifact_name, 'description': description})

            current_output = {"author": self.name,
                "status": "success",
                "message": text,
                "message_for_user": message_for_user,
                "output_artifacts": output_artifacts,
                'output_text':''
            }
            yield self.format_event(text, {'current_output': current_output})
            return








