from typing import AsyncGenerator, List, Dict
from typing_extensions import override
from concurrent.futures import ThreadPoolExecutor
import time
import asyncio
from PIL import Image


from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Content, Blob

from src.logger import logger
from src.agents.experts.image_to_prompt.tool import image_to_prompt_tool
from server.services.token_usage_service import token_usage_service


class ImageToPromptAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate text from image."""

    model_config = {"arbitrary_types_allowed": True}

    def __init__(self, name: str, description: str = "") -> None:
        """Initializes the ImageEditingAgent."""

        super().__init__(
            name=name,
            description=description
        )

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the ImageEditingAgent asynchronously.

        This method orchestrates the sequence of agents to generate an image from text.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image editing process.
        """
        current_parameters = ctx.session.state.get('current_parameters', {})

        if 'input_name' not in current_parameters:
            error_text = f"提供给{self.name}的参数缺失，必须包含：input_name"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})
            return

        input_name = current_parameters['input_name']
        if isinstance(input_name, str):
            input_name = [input_name]

        # prompt enhancement
        tasks = [image_to_prompt_tool(ctx, img_name) for img_name in input_name]
        result = await asyncio.gather(*tasks)
        # generated_prompt_list = []
        # for i, result in enumerate(result_list):
        #     if result['status'] == 'success':
        #         generated_prompt_list.append(result['message'])
        #     else:
        #
        # logger.debug(f"{self.name}: prompt generated: " + '\n\n'.join(generated_prompt_list))


        success_message_list = []
        error_message_list = []
        count = len(input_name)
        for name, result in zip(input_name, result):
            if isinstance(result.get("usage"), dict):
                await token_usage_service.record_external_usage(
                    user_id=ctx.session.user_id,
                    session_id=ctx.session.id,
                    component="expert_tool",
                    agent_name=self.name,
                    model_name=result.get("model_name"),
                    usage=result["usage"],
                )
            if result['status'] == 'success':
                success_message_list.append(f"图片 {name} 的 prompt 为：{result['message']}\n--- \n")
            elif result['status'] == 'error':
                error_message_list.append(f"图片 {name} 的 prompt生成失败，原因是：{result['message']}\n--- \n")

        if len(error_message_list) == count:
            error_text = f"对{count}张图片的prompt反推全部失败，原因：\n\n" + '\n'.join(error_message_list)
            message_for_user = f"对{count}张图片的prompt反推全部失败，原因：\n\n" + '\n'.join(error_message_list)
            current_output = {"author": self.name, "status": "error", "message": error_text,
                              'message_for_user': message_for_user, 'output_text': ''}
            logger.error(error_text)

            yield self.format_event(state_delta={"image_to_prompt_results": error_text})
            yield self.format_event(error_text, state_delta={"current_output": current_output})

            return

        message = f"已完成对{count}张图片的prompt反推，其中{len(success_message_list)}张成功描述。\n\n"
        message_for_user = f"已完成对{count}张图片的prompt反推，其中{len(success_message_list)}张成功描述。"
        output_text = message + '\n'.join(success_message_list + error_message_list)

        current_output = {"author": self.name,
                          "status": "success",
                          "message": message,
                          "message_for_user": message_for_user,
                          'output_text': output_text
                          }

        yield self.format_event(state_delta={"image_to_prompt_results": output_text})
        yield self.format_event(output_text, state_delta={'current_output': current_output})
        return
