import asyncio
from typing_extensions import override
from typing import AsyncGenerator, List, Dict

from google.adk.agents import LlmAgent
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part
from google.genai.types import Content

from conf.system import SYS_CONFIG
from src.agents.experts.image_understanding.tool import image_to_text_tool
from src.logger import logger


class ImageUnderstandingAgent(BaseAgent):
    """
    a custom agent for understanding image
    """

    model_config = {"arbitrary_types_allowed": True}
    def __init__(
        self,
        name: str,
        description: str = ""
    ) :
        super().__init__(
            name = name,
            description = description
        )

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the ImageUnderstandingAgent asynchronously.

        This method achieves understand images.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        logger.info(f"[{self.name}] Starting understanding images.")
        current_parameters = ctx.session.state.get('current_parameters', {})
        if ('input_name' not in current_parameters) or ('mode' not in current_parameters):
            error_text = f"提供给{self.name}的参数缺失，必须包含：input_name, mode"
            message_for_user = f"提供给{self.name}的参数缺失，必须包含：input_name, mode"
            current_output = {"author":self.name, "status": "error", "message": error_text, 'message_for_user': message_for_user, 'output_text':''}
            logger.error(error_text)

            yield self.format_event(state_delta={"image_understanding_results": error_text})
            yield self.format_event(error_text, {"current_output": current_output})

            return


        #rsp: dict = image_to_text_tool(ToolContext(ctx))
        input_name = current_parameters['input_name']
        input_mode = current_parameters["mode"]
        if isinstance(input_name, str):
            input_name = [input_name]
        if isinstance(input_mode, str):
            input_mode = [input_mode]
        count = len(input_name)

        # tasks = [image_to_text_tool(ToolContext(ctx), name, mode) for name, mode in zip(input_name, input_mode)]
        tasks = [image_to_text_tool(ctx, name, mode) for name, mode in zip(input_name, input_mode)]
        result_list = await asyncio.gather(*tasks)

        success_message_list = []
        error_message_list = []
        for name, mode, result in zip(input_name, input_mode, result_list):
            if result['status'] == 'success':
                success_message_list.append(f"图片 {name} 的 {mode}的内容为：{result['message']}\n--- \n")
            elif result['status'] == 'error':
                error_message_list.append(f"图片 {name} 的 {mode}内容描述失败，原因是：{result['message']}\n--- \n")

        if len(error_message_list) == count:
            error_text = f"对{count}张图片的描述全部失败，原因：\n\n" + '\n'.join(error_message_list)
            message_for_user = f"对{count}张图片的描述全部失败，原因：\n\n" + '\n'.join(error_message_list)
            current_output = {"author":self.name, "status": "error", "message": error_text, 'message_for_user':message_for_user, 'output_text':''}
            logger.error(error_text)

            yield self.format_event(state_delta={"image_understanding_results": error_text})
            yield self.format_event(error_text, state_delta={"current_output": current_output})

            return

        message = f"已完成对{count}张图片的理解，其中{len(success_message_list)}张成功描述。\n\n"
        message_for_user = f"已完成对{count}张图片的理解，其中{len(success_message_list)}张成功描述。"
        output_text = message + '\n'.join(success_message_list + error_message_list)

        current_output = {"author":self.name,
            "status": "success",
            "message": message,
            "message_for_user": message_for_user,
            'output_text': output_text
        }

        yield self.format_event(state_delta={"image_understanding_results": output_text})
        yield self.format_event(output_text, state_delta={'current_output':current_output})
        return