from typing import AsyncGenerator, List, Dict
from typing_extensions import override
import time
import asyncio
from PIL import Image
import io

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob, Content


from src.logger import logger
from src.agents.experts.image_generation.tool import (tongyi_text2image_tool,
                                                      prompt_enhancement_tool,
                                                      GPTimage1_text2image_tool,
                                                      nano_banana_image_generation_tool,
                                                      seedream_image_generation_tool)

from src.agents.experts.image_utils import get_image_info_from_bytes
from server.services.token_usage_service import token_usage_service


class ImageGenerationAgent(BaseAgent):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""
    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the ImageGenerationAgent."""

        sub_agents_list: List[BaseAgent] = []
        super().__init__(
            name=name,
            sub_agents=sub_agents_list,
            description=description,
        )


    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event

    @override
    async def _run_async_impl(self, ctx: InvocationContext ) -> AsyncGenerator[Event, None]:
        """
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """


        current_parameters = ctx.session.state.get('current_parameters', {})
        if 'prompt' not in current_parameters:
            error_text = f"提供给{self.name}的参数缺失，必须包含： prompt"
            current_output = {"author":self.name, "status": "error", "message": error_text, 'output_text':''}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})
            return
        tool_name = 'nano_banana'
        aspect_ratio = "9:16"
        resolution = "1K"
        current_info = ''
        if 'tool_name' in current_parameters:
            tool_name = current_parameters['tool_name']
        if 'aspect_ratio' in current_parameters:
            aspect_ratio = current_parameters['aspect_ratio']
        if 'resolution' in current_parameters:
            resolution = current_parameters['resolution']

        if 'current_info' in current_parameters:
            current_info = current_parameters.get('current_info', '')

        original_prompt = current_parameters['prompt']
        if isinstance(original_prompt, str):
            original_prompt = [original_prompt]
        if isinstance(aspect_ratio, str):
            aspect_ratio = [aspect_ratio]
        if isinstance(resolution, str):
            resolution = [resolution]

        same_conf = False
        if len(aspect_ratio) == 1 and len(resolution) == 1:
            same_conf = True
        else:
            if len(original_prompt) != len(aspect_ratio) or len(original_prompt) != len(resolution) :
                error_text = f"提供给{self.name}的参数prompt、aspect_ratio、original_prompt元素个数需要相同。"
                current_output = {"author":self.name, "status": "error", "message": error_text, 'output_text':''}
                logger.error(error_text)

                yield self.format_event(error_text, {"current_output":current_output})
                return

        logger.debug('prompt before enhancement: '+ '\n\n'.join(original_prompt))

        # prompt enhancement
        tasks = [prompt_enhancement_tool(ctx, prompt) for prompt in original_prompt]
        result_list = await asyncio.gather(*tasks)
        prompt_list = []
        for i, result in enumerate(result_list):
            if result['status'] == 'success':
                prompt_list.append(result['message'])
            else:
                logger.warning(f"{self.name}: prompt enhancement failed; using the original prompt")
                prompt_list.append(original_prompt[i])

        logger.debug('prompt after enhancement: ' + '\n\n'.join(prompt_list))
        # if len(current_info) > 0:
        #     prompt_list_with_info = []
        #     for p in prompt_list:
        #         prompt_list_with_info.append(p + '\n reference information: ' + current_info)
        #
        #     prompt_list = prompt_list_with_info


        if tool_name == 'nano_banana':
            if same_conf:
                tasks = [
                    nano_banana_image_generation_tool(
                        ctx, prompt, aspect_ratio=aspect_ratio[0], resolution=resolution[0]
                    )
                    for i, prompt in enumerate(prompt_list)
                ]
            else:
                tasks = [
                    nano_banana_image_generation_tool(
                        ctx, prompt, aspect_ratio=aspect_ratio[i], resolution=resolution[i]
                    )
                    for i, prompt in enumerate(prompt_list)
                ]
            result_list = await asyncio.gather(*tasks)
        elif tool_name == 'seedream':
            tasks = [seedream_image_generation_tool(prompt) for prompt in prompt_list]
            result_list = await asyncio.gather(*tasks)
        else:
            tasks = [GPTimage1_text2image_tool(prompt) for prompt in prompt_list]
            result_list = await asyncio.gather(*tasks)

        output_artifacts = []
        message = []
        for i, (prompt, result) in enumerate(zip(prompt_list, result_list)):
            usage = result.get("usage")
            if isinstance(usage, dict):
                await token_usage_service.record_external_usage(
                    user_id=ctx.session.user_id,
                    session_id=ctx.session.id,
                    component="expert_tool",
                    agent_name=self.name,
                    model_name=result.get("model_name"),
                    usage=usage,
                )
            if result['status'] == 'error':
                message.append(f"第{i+1}个图片生成失败，原因：{result['message']}")
            else:
                message.append(f"第{i+1}个图片生成成功")
                artifact_name = f"step{ctx.session.state.get('step')+1}_generation_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=result["message"]))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id, filename=artifact_name, artifact=artifact_part
                )

                basic_info = get_image_info_from_bytes(result["message"])
                description = f"第{ctx.session.state.get('step')+1}步由图片生成工具生成的第{i+1}张图片，prompt为：{prompt} \n\n 生成后的图像基本信息为：{basic_info}"

                output_artifacts.append({'name': artifact_name, 'description': description})
        
        if len(output_artifacts) == 0:
            message = f"全部{len(result_list)}张图片生成失败。{','.join(message)}"
            message_for_user =  message
            logger.error(message)
            current_output = {"author": self.name, 'status': 'error', 'message': message, 'message_for_user': message_for_user, 'output_text':''}
            
        else:
            message = f"已完成{len(result_list)}个任务的生成：{','.join(message)}"
            message_for_user = f"已完成任务的图像生成工作"
            logger.info(message)
            current_output = {"author": self.name, 'status': 'success', 'message': message, 'message_for_user':message_for_user, 'output_artifacts': output_artifacts, 'output_text':''}

        yield self.format_event(message, {"current_output": current_output})
        return
