from typing import AsyncGenerator, List, Dict
from typing_extensions import override
import time
import asyncio
from PIL import Image
import io

from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob, Content


from src.logger import logger
from src.agents.experts.image_generation_reasoning.tool import nano_banana_image_generation_tool

from src.agents.experts.image_utils import get_image_info_from_bytes
from server.services.token_usage_service import token_usage_service


class ReasoningImageGenerationAgent(BaseAgent):
    """Generate images for complex reasoning-heavy text prompts without prompt enhancement."""
    model_config = {"arbitrary_types_allowed": True}

    def __init__(
        self, name: str, description: str = "") -> None:
        """Initializes the ImageGenerationAgent."""

        sub_agents_list: List[BaseAgent] = []
        super().__init__(
            name=name,
            sub_agents=sub_agents_list,
            description=description,
        )


    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event

    @override
    async def _run_async_impl(self, ctx: InvocationContext ) -> AsyncGenerator[Event, None]:
        """
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """


        current_parameters = ctx.session.state.get('current_parameters', {})
        if 'prompt' not in current_parameters:
            error_text = f"提供给{self.name}的参数缺失，必须包含： prompt"
            current_output = {"author":self.name, "status": "error", "message": error_text, 'output_text':''}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})
            return

        aspect_ratio = "9:16"
        resolution = "1K"
        current_info = ''

        if 'aspect_ratio' in current_parameters:
            aspect_ratio = current_parameters['aspect_ratio']
        if 'resolution' in current_parameters:
            resolution = current_parameters['resolution']

        if 'current_info' in current_parameters:
            current_info = current_parameters.get('current_info', '')

        prompt = current_parameters['prompt']

        if len(current_info) > 0:
            prompt = prompt + '\n reference information: ' + current_info

        results = await nano_banana_image_generation_tool(ctx, prompt, aspect_ratio=aspect_ratio, resolution=resolution)
        if isinstance(results.get("usage"), dict):
            await token_usage_service.record_external_usage(
                user_id=ctx.session.user_id,
                session_id=ctx.session.id,
                component="expert_tool",
                agent_name=self.name,
                model_name=results.get("model_name"),
                usage=results["usage"],
            )

        output_artifacts = []
        message = []
        # print(results)
        if results['status'] == 'error':
            message.append(f"图片生成失败，原因：{results['message']}")
        else:
            for i, img in enumerate(results['images']):

                message.append(f"第{i+1}个图片生成成功")
                artifact_name = f"step{ctx.session.state.get('step')+1}_reasoning_generation_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=img))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id, filename=artifact_name, artifact=artifact_part
                )

                basic_info = get_image_info_from_bytes(img)
                description = f"第{ctx.session.state.get('step')+1}步由图片生成工具生成的第{i+1}张图片，prompt为：{prompt} \n\n 生成后的图像基本信息为：{basic_info}"

                output_artifacts.append({'name': artifact_name, 'description': description})
        
        if len(output_artifacts) == 0:
            message = f"图片生成失败。{','.join(message)}"
            message_for_user =  message
            logger.error(message)
            current_output = {"author": self.name, 'status': 'error', 'message': message, 'message_for_user': message_for_user, 'output_text':''}
            
        else:
            message = f"已完成图像生成：{','.join(message)}"
            message_for_user = f"已完成图像生成工作。"
            logger.info(message)
            current_output = {"author": self.name, 'status': 'success', 'message': message, 'message_for_user': message_for_user, 'output_artifacts': output_artifacts, 'output_text': ''}

        yield self.format_event(message, {"current_output": current_output})
        return
