# import asyncio
# import time
# from concurrent.futures import ThreadPoolExecutor
from typing import AsyncGenerator, List, Dict
from typing_extensions import override

from google.genai.types import Content
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob

from conf.system import SYS_CONFIG
from src.logger import logger
from src.agents.experts.search.tool import retrieve_image_by_text, DDGS_search, tavily_search


class SearchAgent(BaseAgent):
    """
    a custom agent for search image or text
    """

    model_config = {"arbitrary_types_allowed": True}
    max_search_count: int = 10
    def __init__(
        self,
        name: str,
        description: str = "",
        max_search_count: int = 10
    ) :
        super().__init__(
            name = name,
            description = description
        )
        self.max_search_count = max_search_count

    def format_event(self, content_text: str=None, state_delta: Dict=None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the SearchAgent asynchronously.

        This method achieves retrieve or download images.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        current_parameters = ctx.session.state.get('current_parameters', {})
        current_search_count = ctx.session.state.get('step')
        search_count_delta = {'search_count': current_search_count + 1}
        yield self.format_event(state_delta=search_count_delta)

        if current_search_count > self.max_search_count:
            error_text = "已经到达本次session使用搜索次数的上限。因此对当前的query无搜索结果返回。"
            current_output = {"author": self.name, "status": "error", "message": error_text, "output_text": "no output text"}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})

            return
        
        if ('query' not in current_parameters) or ('mode' not in current_parameters):
            error_text = "提供给SearchAgent的参数缺失，必须包含：query, mode"
            current_output = {"author": self.name, "status": "error", "message": error_text, "output_text": "no output text"}
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output": current_output})

            return
        
        if current_parameters['mode'] not in ['image', 'text', 'all']:
            logger.warning(f"SearchAgent got invalid parameters: mode: {current_parameters['mode']}, set to 'all'")
            current_parameters['mode'] = 'all'

        logger.info(f"[{self.name}] start searching. mode: {current_parameters['mode']}, query: {current_parameters['query']}")
        if current_parameters['mode'] == 'image':
            current_output = await self.search_image(ctx)
            yield self.format_event(current_output['message'], {"current_output": current_output})
            return
        
        if current_parameters['mode'] == 'text':
            current_output = await self.search_text(ctx)
            yield self.format_event(current_output['message'], {"current_output": current_output})
            yield self.format_event('long text to extract', {"long_text_to_extract": current_output})
            return
        
        if current_parameters['mode'] == 'all':
            image_output = await self.search_image(ctx)
            text_output = await self.search_text(ctx)

            if image_output['status'] == 'error' and text_output['status'] == 'error':
                error_text = '\n'.join([image_output['message'], text_output['message']])
                current_output = {"author": self.name,
                    'status': 'error',
                    'message': error_text,
                    'output_text': ''
                }
                yield self.format_event(error_text, {"current_output": current_output})
            
            else:
                message_all = '\n'.join([image_output['message'], text_output['message']])
                current_output = {"author": self.name,
                    'status': 'success',
                    'message': message_all,
                    'output_text':  text_output['output_text']
                }
                if image_output['status'] == 'success' and 'output_artifacts' in image_output:
                    current_output['output_artifacts'] = image_output['output_artifacts']

                # if text_output['status']=='success':
                #     current_output['message'] += text
                # else:
                #     current_output['message'] += f"\n{text_output['message']}"
                
                yield self.format_event(message_all, {"current_output": current_output})
                
            return
        
        
    async def search_image(self, ctx: InvocationContext):
        rsp = await retrieve_image_by_text(ToolContext(ctx))

        if rsp["status"] == "error":
            error_text = f"{self.name} 搜索图片时错误: {rsp['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'output_text':''}
            logger.error(error_text)
            return current_output
        else:
            # save image:
            output_artifacts = []
            for i, img_binary in enumerate(rsp['message']):
                artifact_name = f"step{ctx.session.state.get('step')+1}_search_output{i}.png"
                artifact_part = Part(inline_data=Blob(mime_type='image/png', data=img_binary))

                await ctx.artifact_service.save_artifact(
                    app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id, filename=artifact_name, artifact=artifact_part
                )

                output_artifacts.append({'name': artifact_name, 'description': f"图片搜索工具按照query：{ctx.session.state['current_parameters']['query']}的搜索结果"})

            text = f"{self.name} 已完成图片搜索，返回{len(rsp['message'])}张图片。它们的文件名称分别为:{[','.join(art['name'] for art in output_artifacts)]}"

            current_output = {"author": self.name,
                "status": "success",
                "message": text,
                "output_artifacts": output_artifacts,
                'output_text': ''
            }
            
            return current_output
        
    async def search_text(self, ctx: InvocationContext):
        rsp = await tavily_search(ToolContext(ctx))
        # rsp = await DDGS_search(ToolContext(ctx))
        logger.info(str(rsp))

        if rsp['status'] == 'error':
            error_text = f"{self.name} 搜索文本时错误: {rsp['message']}"
            message_for_user = f"搜索文本时错误: {rsp['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user':message_for_user, 'output_text': ''}
            logger.error(error_text)
            return current_output
        else:
            text = f"{self.name} 已完成文本搜索。"
            message_for_user = "已完成文本搜索。"
            current_output = {"author": self.name,
                "status": "success",
                "message": text,
                "message_for_user": message_for_user,
                'output_text': rsp['message']
            }
            return current_output










