import datetime
import json, uuid
import re
import os.path
from typing import AsyncGenerator, List, Optional, Any, Dict, Tuple


from google.adk.agents import BaseAgent, LlmAgent
from src.llm.model_factory import build_model_and_config
from google.adk.agents.invocation_context import InvocationContext
from google.adk.artifacts import InMemoryArtifactService
from google.adk.events import Event, EventActions
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai.types import Content, Part, Blob

from src.logger import logger
from conf.system import SYS_CONFIG
from conf.agent import experts_list
from src.utils import database_op_with_retry
from server.services.token_usage_service import token_usage_service

available_agents: str = '\n'.join([str(expert) for expert in experts_list if expert.enable])
time_str = datetime.date.today().strftime("%Y-%m-%d")

def clean_and_parse_json(json_string: str) -> Dict[str, Any]:
    cleaned_string = re.sub(r'^```(json)?\s*|\s*```$', '', json_string.strip(), flags=re.MULTILINE)
    try:
        return json.loads(cleaned_string)
    except json.JSONDecodeError:
        logger.error(f"Failed to parse JSON. Raw string: '{json_string}'")
        return {}
    
class ExecutorAgent(BaseAgent):
    """
    The executor agent that generate plan
    """
    planner: LlmAgent
    executor_replan_enabled: bool

    def __init__(
        self,
        name:str,
        description:str,
        llm_model: str = '',
        executor_replan_enabled: bool = False,
    ):
        if not llm_model:
            llm_model = SYS_CONFIG.executor_llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        llm_model, llm_config = build_model_and_config(llm_model)

        planner = LlmAgent(
            name="PlannerAgent",
            model=llm_model,
            generate_content_config=llm_config,
            description='Analyze input request, output a plan in json format in order to successive execution.',
            instruction=EXECUTOR_INSTRUCTION + available_agents + '\n\n'
        )

        super().__init__(
            name=name,
            description=description,
            planner = planner,
            executor_replan_enabled = executor_replan_enabled
        )

        

    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Run the executor agent
        if self.executor_replan_enabled==True: executor will generate a plan on itself
        otherwise, it directly use the plan stored in state

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the plan generation process.

        """
        
        async for event in self.planner.run_async(ctx):
            if event.is_final_response() and event.content and event.content.parts:
                final_response_text = ''
                text_part = next((part.text for part in event.content.parts if part.text), None)
                if text_part:
                    final_response_text = text_part

                # new plan generated by executor agent
                plan = clean_and_parse_json(final_response_text)

                if 'next_agent' in plan and 'parameters' in plan:
                    # yield Event(author='api_server', content=None, actions=EventActions(state_delta=plan))
                    yield Event(author='api_server', content=None, actions=EventActions(state_delta={"current_plan": plan}))


class Executor:
    def __init__(
        self,
        session_service: InMemorySessionService,
        artifact_service: InMemoryArtifactService,
        app_name: str = SYS_CONFIG.app_name,
        save_dir: str = '',
        uid: str = '',
        sid: str = '',
        username: str = '',
        llm_model: str = '',
        expert_runners: Dict[str, Runner] = {},
        executor_replan_enabled: bool = False
    ) -> None:
        self.app_name = app_name
        self.session_service = session_service
        self.artifact_service = artifact_service
        self.save_dir = save_dir
        self.uid = uid
        self.sid = sid
        self.username = username
        self.executor_replan_enabled = executor_replan_enabled

        if not llm_model:
            llm_model = SYS_CONFIG.executor_llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        self.expert_runners = expert_runners

        self.executor_agent = ExecutorAgent(
            name="ExecutorAgent",
            description="",
            llm_model=llm_model,
            executor_replan_enabled=executor_replan_enabled
        )

        self.executor_runner = Runner(agent=self.executor_agent, app_name=self.app_name, session_service=self.session_service, artifact_service=self.artifact_service)

    async def run_agent_and_log_events(self, runner: Runner, user_id: str, session_id: str, new_message: Optional[Content] = None) -> str:
        final_response_text = ""
        async for event in runner.run_async(user_id=user_id, session_id=session_id, new_message=new_message):
            logger.debug(f"Event: {event.model_dump_json(indent=2, exclude_none=True)}")
            component = "expert" if runner.agent.name != "ExecutorAgent" else "executor"
            await token_usage_service.record_event_usage(
                user_id=user_id,
                session_id=session_id,
                event=event,
                component=component,
                agent_name=getattr(event, "author", None) or runner.agent.name,
                model_name=getattr(event, "model_version", None),
            )
            if event.is_final_response() and event.content and event.content.parts:
                text_part = next((part.text for part in event.content.parts if part.text), None)
                if text_part:
                    final_response_text = text_part
                    logger.info(f"[{runner.agent.name}] final response text: '{final_response_text}'")
        return final_response_text
    
    async def add_event(self, text:str='', state_delta:Dict=None):
        if state_delta is None:
            state_delta = {}

        if text:
            event = Event(
                author='api_server',
                content=Content(role='model', parts=[Part(text=text)]),
                actions=EventActions(state_delta=state_delta)
            )
        else:
            event = Event(
                author='api_server',
                actions=EventActions(state_delta=state_delta)
            )

        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )

        # await self.session_service.append_event(current_session, event)
        await database_op_with_retry(
            self.session_service.append_event,
            session=current_session,
            event=event,
            logger=logger,
            op_name="add_event_append_event"
        )

    async def save_artifact(self, art_name: str, current_uid:str, current_sid:str):
        art_part = await self.artifact_service.load_artifact(
            app_name=self.app_name, user_id=self.uid, session_id=self.sid, filename=art_name
        )

        if art_part is not None:
            art_name = f"{current_uid}_{current_sid}_{art_name}"
            art_path = os.path.join(self.save_dir, art_name)
            with open(art_path, mode='wb') as f:
                f.write(art_part.inline_data.data)
        else:
            logger.error(f'load {art_name} return none and save failed')
            return None
        return art_path
    
    async def check_paramters_valid(self, agent_name: str, params_for_expert: Dict[str, Any]) -> str:
        error_text = ''
        error_arifact_names = []

        if agent_name not in self.expert_runners:
            error_text = f"Executor决策了未知的Agent: '{agent_name}'，它不在提供的agent列表中"
            return error_text

        if 'input_name' in params_for_expert:
            art_list = await self.artifact_service.list_artifact_keys(
                app_name=self.app_name, user_id=self.uid, session_id=self.sid
            )

            input_names = []
            if isinstance(params_for_expert['input_name'], str):
                input_names = [params_for_expert['input_name']]
            elif isinstance(params_for_expert['input_name'], list):
                input_names = params_for_expert['input_name']
            else:
                error_text += f"当前的规划中的parameters['input_name']格式错误，需要为string或list"
                return error_text

            for name in input_names:
                if name in art_list:
                    continue

                logger.info(art_list)
                error_arifact_names.append(name)

        if len(error_arifact_names) > 0:
            error_text += f"Executor选择了未知的artifact: {', '.join([f'\"{name}\"' for name in error_arifact_names])}，它们不在artifacts列表中"

        return error_text

    async def execute_plan(self):
        """Execute the current plan stored in session state and persist the result."""
        if self.executor_replan_enabled:
            new_message = Content(role='user', parts=[Part(
                text="根据原始任务和当前state，生成下一步的操作步骤。如果之前生成了整个任务所有步骤的规划，请忽略。你只需要关注整体任务和当前的state。")])
            await self.run_agent_and_log_events(self.executor_runner, session_id=self.sid, user_id=self.uid, new_message=new_message) #

        # load state['current_plan']
        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )


        plan = current_session.state.get('current_plan') 

        next_agent_name = plan.get("next_agent")
        params_for_expert = plan.get("parameters", {})
        final_summary = plan.get("summary", {})

        error_text = await self.check_paramters_valid(next_agent_name, params_for_expert)
        if error_text:
            logger.error(error_text)
            

            current_output = {
                "author": "Executor",
                "status": "error",
                "message": error_text,
                "output_artifacts": [],
                "output_text": ""
            }
        else:
            await self.add_event(state_delta={'current_parameters': params_for_expert})
            expert_runner = self.expert_runners[next_agent_name]
            new_message = Content(role='user', parts=[Part(text="根据原始任务和当前的plan以及对应的输入参数，调用对应的agent来执行")])
            await self.run_agent_and_log_events(expert_runner, user_id=self.uid, session_id=self.sid, new_message=new_message)
            current_output = {}

        # {
        # }



        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )
        if not current_output:
            current_output = current_session.state.get('current_output')
        
        current_step = current_session.state.get('step')
        artifacts_history = current_session.state.get('artifacts_history')
        text_history = current_session.state.get('text_history')
        message_history = current_session.state.get('message_history')
        summary_history = current_session.state.get('summary_history')

        if not current_output:
            current_output = {'status': 'pending'}

        state_delta = {
            'step': current_step + 1,
            'current_plan': {},
        }

        if current_output['status'] == 'success' and 'output_artifacts' in current_output:
            for art in current_output['output_artifacts']:
                current_sid = current_session.state['sid']
                current_uid = current_session.state['uid']
                logger.info(f"saving artifact {art['name']}")
                art_path = await self.save_artifact(art['name'], current_uid, current_sid)
                art['path'] = art_path

                logger.info(f"saved to {art_path}")

        if current_output['status'] == 'success':
            if 'output_artifacts' in current_output:
                state_delta['new_artifacts'] = current_output['output_artifacts']
                state_delta['artifacts_history'] = artifacts_history + [current_output['output_artifacts']]
            else:
                state_delta['new_artifacts'] = []
                state_delta['artifacts_history'] = artifacts_history + [[]]

            if 'output_text' in current_output and len(current_output['output_text']) > 0:
                state_delta['text_history'] = text_history + [current_output['author'] + '的 output_text: \n' + str(current_output['output_text']) + '\n']
            else:
                state_delta['text_history'] = text_history + [None]

            state_delta['summary_history'] = summary_history + [final_summary]

            state_delta['message_history'] = message_history + [current_output['message']]

            await self.add_event(text=f"第{current_step+1}轮执行已完成。这一步的原始目标：`{final_summary}`，执行完成后的总结：`{current_output['message']}`", state_delta=state_delta)

        elif current_output['status'] == 'error':
            state_delta['new_artifacts'] = []
            state_delta['artifacts_history'] = artifacts_history + [[]]
            state_delta['text_history'] = text_history + [None]
            state_delta['message_history'] = message_history + [current_output['message']]
            state_delta['summary_history'] = summary_history + [final_summary]

            await self.add_event(text=f"第{current_step+1}轮专家执行出错。这一步的原始目标：`{final_summary}`, 执行错误描述：`{current_output['message']}`。当前步骤目标可能未完成，需要视情况重新执行或使用新的参数或方法。", state_delta=state_delta)

        return current_output


EXECUTOR_INSTRUCTION = """
你是一个复杂任务的执行AI。你的任务是在一个循环中持续分析一个共享的“状态(state)”，并决定下一步需要调用哪个专家Agent以及参数，直到整个多步骤的用户任务完成。

**你需要查看对话历史和state中的参数来了解当前的任务规划和状态
之前生成的全局所有步骤规划如下，它可能存在也可能不存在：{global_plan}


**你的唯一输出必须是一个JSON对象。**
**JSON 输出格式:**
```json
{{
    "next_agent": "AgentName",
    "parameters": {{
    "param1_for_agent": "value1"
    }},
    "summary": "对你当前决策的简短总结，会展示给用户。"
}}
```

# 关键指令:
1.  **发出结束信号**: 当输出单步规划时且你判断整个用户的初始任务已经彻底完成时，你必须将 `next_agent` 的值设置为 `null` 或 `"FINISH"`。这是终止循环的唯一方式。
2.  **利用中间产物**: 你必须检查其他Agent生成的输出文件路径（路径中通常包含'output'），之前步骤的对话内容中会包含文件输出名称，使用这些输出来准备下一步的参数。
3.  **精确任务分派**: 对于图像编辑，要特别注意用户的意图。如果用户提到“修复”、“替换特定区域”、“移除某个物体”或提供了蒙版图，你应该使用专门的局部重绘功能。

# 工作流程:

1.  **分析当前状态**:
    - 仔细阅读 `{user_prompt}`以及当前的任务规划，来理解当前任务的执行情况。

2.  **决策与参数准备**:
    - 如果任务未完成，决定下一步需要哪个专家。
    - 为该专家准备一个包含所有必需参数的 `parameters` 字典。


# 专家的使用方法
 - 你支持 Nano Banana 这个知名的图像编辑模型，只需要在指令里面明确说一下即可。
 - ArtKnowledgeAgent 具备丰富的设计知识，如果用户任务是设计类的，并且没有非常详细的设计细节说明（即用户是设计小白），可以问下 ArtKnowledgeAgent 意见。
 - 在HTML2ImageAgent 之后不要再次编辑图像，因为会破坏页面的呈现效果。
 - 图像编辑类任务不要使用 ArtKnowledgeAgent。
 - 不要反复使用图像编辑agent。反复修改的次数不要超过3次。
 - nana banana 擅长编辑、抠图等，但是放置文字方面 gpt-image更好一点。
 
# 沟通语言
 - 需要显示给用户看的信息以及中间思考过程，请使用使用用户的语言类型。

# 你可以使用的专家 Agent 列表和所需参数: \n
"""
